### ISSUE TITLE
Missing license

### ISSUE THREAD

**Issue by sweeneyb** [FidelityInternational/concourse-teams-notification-resource#9]
This project is missing a license, which limits reuse in corporate environments.  Would you be able to attach a license?  If you let me know which license you'd like, I can submit a merge request to get it in the right spot.

Thanks!

**Comment by jimconner** [comment]
Thanks for raising this issue. It's always nice to know that your code is useful to others. I've now added MIT license into this repo, so you can do as you please with whatever code is in here.
